// Generated from react-international-phone countryData.ts (data source:
// bl00mber/react-phone-input-2 rawCountries.js). DO NOT EDIT BY HAND.
// Regenerate: node scripts/gen-countries.cjs
export interface CountryRecord {
  /** English display name used for search. */
  name: string
  /** ISO 3166-1 alpha-2, lowercase. */
  iso2: string
  /** International calling code WITHOUT leading +. */
  code: string
}

export const COUNTRIES: CountryRecord[] = [
  { name: '"Côte d\'Ivoire"', iso2: 'ci', code: '225' },
  { name: 'Afghanistan', iso2: 'af', code: '93' },
  { name: 'Albania', iso2: 'al', code: '355' },
  { name: 'Algeria', iso2: 'dz', code: '213' },
  { name: 'Andorra', iso2: 'ad', code: '376' },
  { name: 'Angola', iso2: 'ao', code: '244' },
  { name: 'Antigua and Barbuda', iso2: 'ag', code: '1268' },
  { name: 'Argentina', iso2: 'ar', code: '54' },
  { name: 'Armenia', iso2: 'am', code: '374' },
  { name: 'Aruba', iso2: 'aw', code: '297' },
  { name: 'Australia', iso2: 'au', code: '61' },
  { name: 'Austria', iso2: 'at', code: '43' },
  { name: 'Azerbaijan', iso2: 'az', code: '994' },
  { name: 'Bahamas', iso2: 'bs', code: '1242' },
  { name: 'Bahrain', iso2: 'bh', code: '973' },
  { name: 'Bangladesh', iso2: 'bd', code: '880' },
  { name: 'Barbados', iso2: 'bb', code: '1246' },
  { name: 'Belarus', iso2: 'by', code: '375' },
  { name: 'Belgium', iso2: 'be', code: '32' },
  { name: 'Belize', iso2: 'bz', code: '501' },
  { name: 'Benin', iso2: 'bj', code: '229' },
  { name: 'Bhutan', iso2: 'bt', code: '975' },
  { name: 'Bolivia', iso2: 'bo', code: '591' },
  { name: 'Bosnia and Herzegovina', iso2: 'ba', code: '387' },
  { name: 'Botswana', iso2: 'bw', code: '267' },
  { name: 'Brazil', iso2: 'br', code: '55' },
  { name: 'British Indian Ocean Territory', iso2: 'io', code: '246' },
  { name: 'Brunei', iso2: 'bn', code: '673' },
  { name: 'Bulgaria', iso2: 'bg', code: '359' },
  { name: 'Burkina Faso', iso2: 'bf', code: '226' },
  { name: 'Burundi', iso2: 'bi', code: '257' },
  { name: 'Cambodia', iso2: 'kh', code: '855' },
  { name: 'Cameroon', iso2: 'cm', code: '237' },
  { name: 'Cape Verde', iso2: 'cv', code: '238' },
  { name: 'Central African Republic', iso2: 'cf', code: '236' },
  { name: 'Chad', iso2: 'td', code: '235' },
  { name: 'Chile', iso2: 'cl', code: '56' },
  { name: 'China', iso2: 'cn', code: '86' },
  { name: 'Colombia', iso2: 'co', code: '57' },
  { name: 'Comoros', iso2: 'km', code: '269' },
  { name: 'Congo', iso2: 'cd', code: '243' },
  { name: 'Congo', iso2: 'cg', code: '242' },
  { name: 'Costa Rica', iso2: 'cr', code: '506' },
  { name: 'Croatia', iso2: 'hr', code: '385' },
  { name: 'Cuba', iso2: 'cu', code: '53' },
  { name: 'Curaçao', iso2: 'cw', code: '599' },
  { name: 'Cyprus', iso2: 'cy', code: '357' },
  { name: 'Czech Republic', iso2: 'cz', code: '420' },
  { name: 'Denmark', iso2: 'dk', code: '45' },
  { name: 'Djibouti', iso2: 'dj', code: '253' },
  { name: 'Dominica', iso2: 'dm', code: '1767' },
  { name: 'Ecuador', iso2: 'ec', code: '593' },
  { name: 'Egypt', iso2: 'eg', code: '20' },
  { name: 'El Salvador', iso2: 'sv', code: '503' },
  { name: 'Equatorial Guinea', iso2: 'gq', code: '240' },
  { name: 'Eritrea', iso2: 'er', code: '291' },
  { name: 'Estonia', iso2: 'ee', code: '372' },
  { name: 'Ethiopia', iso2: 'et', code: '251' },
  { name: 'Faroe Islands', iso2: 'fo', code: '298' },
  { name: 'Fiji', iso2: 'fj', code: '679' },
  { name: 'Finland', iso2: 'fi', code: '358' },
  { name: 'France', iso2: 'fr', code: '33' },
  { name: 'French Guiana', iso2: 'gf', code: '594' },
  { name: 'French Polynesia', iso2: 'pf', code: '689' },
  { name: 'Gabon', iso2: 'ga', code: '241' },
  { name: 'Gambia', iso2: 'gm', code: '220' },
  { name: 'Georgia', iso2: 'ge', code: '995' },
  { name: 'Germany', iso2: 'de', code: '49' },
  { name: 'Ghana', iso2: 'gh', code: '233' },
  { name: 'Gibraltar', iso2: 'gi', code: '350' },
  { name: 'Greece', iso2: 'gr', code: '30' },
  { name: 'Greenland', iso2: 'gl', code: '299' },
  { name: 'Grenada', iso2: 'gd', code: '1473' },
  { name: 'Guadeloupe', iso2: 'gp', code: '590' },
  { name: 'Guam', iso2: 'gu', code: '1671' },
  { name: 'Guatemala', iso2: 'gt', code: '502' },
  { name: 'Guinea', iso2: 'gn', code: '224' },
  { name: 'Guinea-Bissau', iso2: 'gw', code: '245' },
  { name: 'Guyana', iso2: 'gy', code: '592' },
  { name: 'Haiti', iso2: 'ht', code: '509' },
  { name: 'Honduras', iso2: 'hn', code: '504' },
  { name: 'Hong Kong', iso2: 'hk', code: '852' },
  { name: 'Hungary', iso2: 'hu', code: '36' },
  { name: 'Iceland', iso2: 'is', code: '354' },
  { name: 'India', iso2: 'in', code: '91' },
  { name: 'Indonesia', iso2: 'id', code: '62' },
  { name: 'Iran', iso2: 'ir', code: '98' },
  { name: 'Iraq', iso2: 'iq', code: '964' },
  { name: 'Ireland', iso2: 'ie', code: '353' },
  { name: 'Israel', iso2: 'il', code: '972' },
  { name: 'Italy', iso2: 'it', code: '39' },
  { name: 'Jamaica', iso2: 'jm', code: '1876' },
  { name: 'Japan', iso2: 'jp', code: '81' },
  { name: 'Jordan', iso2: 'jo', code: '962' },
  { name: 'Kazakhstan', iso2: 'kz', code: '7' },
  { name: 'Kenya', iso2: 'ke', code: '254' },
  { name: 'Kiribati', iso2: 'ki', code: '686' },
  { name: 'Kosovo', iso2: 'xk', code: '383' },
  { name: 'Kuwait', iso2: 'kw', code: '965' },
  { name: 'Kyrgyzstan', iso2: 'kg', code: '996' },
  { name: 'Laos', iso2: 'la', code: '856' },
  { name: 'Latvia', iso2: 'lv', code: '371' },
  { name: 'Lebanon', iso2: 'lb', code: '961' },
  { name: 'Lesotho', iso2: 'ls', code: '266' },
  { name: 'Liberia', iso2: 'lr', code: '231' },
  { name: 'Libya', iso2: 'ly', code: '218' },
  { name: 'Liechtenstein', iso2: 'li', code: '423' },
  { name: 'Lithuania', iso2: 'lt', code: '370' },
  { name: 'Luxembourg', iso2: 'lu', code: '352' },
  { name: 'Macau', iso2: 'mo', code: '853' },
  { name: 'Macedonia', iso2: 'mk', code: '389' },
  { name: 'Madagascar', iso2: 'mg', code: '261' },
  { name: 'Malawi', iso2: 'mw', code: '265' },
  { name: 'Malaysia', iso2: 'my', code: '60' },
  { name: 'Maldives', iso2: 'mv', code: '960' },
  { name: 'Mali', iso2: 'ml', code: '223' },
  { name: 'Malta', iso2: 'mt', code: '356' },
  { name: 'Marshall Islands', iso2: 'mh', code: '692' },
  { name: 'Martinique', iso2: 'mq', code: '596' },
  { name: 'Mauritania', iso2: 'mr', code: '222' },
  { name: 'Mauritius', iso2: 'mu', code: '230' },
  { name: 'Mexico', iso2: 'mx', code: '52' },
  { name: 'Micronesia', iso2: 'fm', code: '691' },
  { name: 'Moldova', iso2: 'md', code: '373' },
  { name: 'Monaco', iso2: 'mc', code: '377' },
  { name: 'Mongolia', iso2: 'mn', code: '976' },
  { name: 'Montenegro', iso2: 'me', code: '382' },
  { name: 'Morocco', iso2: 'ma', code: '212' },
  { name: 'Mozambique', iso2: 'mz', code: '258' },
  { name: 'Myanmar', iso2: 'mm', code: '95' },
  { name: 'Namibia', iso2: 'na', code: '264' },
  { name: 'Nauru', iso2: 'nr', code: '674' },
  { name: 'Nepal', iso2: 'np', code: '977' },
  { name: 'Netherlands', iso2: 'nl', code: '31' },
  { name: 'New Caledonia', iso2: 'nc', code: '687' },
  { name: 'New Zealand', iso2: 'nz', code: '64' },
  { name: 'Nicaragua', iso2: 'ni', code: '505' },
  { name: 'Niger', iso2: 'ne', code: '227' },
  { name: 'Nigeria', iso2: 'ng', code: '234' },
  { name: 'North Korea', iso2: 'kp', code: '850' },
  { name: 'Norway', iso2: 'no', code: '47' },
  { name: 'Oman', iso2: 'om', code: '968' },
  { name: 'Pakistan', iso2: 'pk', code: '92' },
  { name: 'Palau', iso2: 'pw', code: '680' },
  { name: 'Palestine', iso2: 'ps', code: '970' },
  { name: 'Panama', iso2: 'pa', code: '507' },
  { name: 'Papua New Guinea', iso2: 'pg', code: '675' },
  { name: 'Paraguay', iso2: 'py', code: '595' },
  { name: 'Peru', iso2: 'pe', code: '51' },
  { name: 'Philippines', iso2: 'ph', code: '63' },
  { name: 'Poland', iso2: 'pl', code: '48' },
  { name: 'Portugal', iso2: 'pt', code: '351' },
  { name: 'Qatar', iso2: 'qa', code: '974' },
  { name: 'Réunion', iso2: 're', code: '262' },
  { name: 'Romania', iso2: 'ro', code: '40' },
  { name: 'Rwanda', iso2: 'rw', code: '250' },
  { name: 'Saint Kitts and Nevis', iso2: 'kn', code: '1869' },
  { name: 'Saint Lucia', iso2: 'lc', code: '1758' },
  { name: 'Saint Pierre & Miquelon', iso2: 'pm', code: '508' },
  { name: 'Saint Vincent and the Grenadines', iso2: 'vc', code: '1784' },
  { name: 'Samoa', iso2: 'ws', code: '685' },
  { name: 'San Marino', iso2: 'sm', code: '378' },
  { name: 'São Tomé and Príncipe', iso2: 'st', code: '239' },
  { name: 'Saudi Arabia', iso2: 'sa', code: '966' },
  { name: 'Senegal', iso2: 'sn', code: '221' },
  { name: 'Serbia', iso2: 'rs', code: '381' },
  { name: 'Seychelles', iso2: 'sc', code: '248' },
  { name: 'Sierra Leone', iso2: 'sl', code: '232' },
  { name: 'Singapore', iso2: 'sg', code: '65' },
  { name: 'Slovakia', iso2: 'sk', code: '421' },
  { name: 'Slovenia', iso2: 'si', code: '386' },
  { name: 'Solomon Islands', iso2: 'sb', code: '677' },
  { name: 'Somalia', iso2: 'so', code: '252' },
  { name: 'South Africa', iso2: 'za', code: '27' },
  { name: 'South Korea', iso2: 'kr', code: '82' },
  { name: 'South Sudan', iso2: 'ss', code: '211' },
  { name: 'Spain', iso2: 'es', code: '34' },
  { name: 'Sri Lanka', iso2: 'lk', code: '94' },
  { name: 'Sudan', iso2: 'sd', code: '249' },
  { name: 'Suriname', iso2: 'sr', code: '597' },
  { name: 'Swaziland', iso2: 'sz', code: '268' },
  { name: 'Sweden', iso2: 'se', code: '46' },
  { name: 'Switzerland', iso2: 'ch', code: '41' },
  { name: 'Syria', iso2: 'sy', code: '963' },
  { name: 'Taiwan', iso2: 'tw', code: '886' },
  { name: 'Tajikistan', iso2: 'tj', code: '992' },
  { name: 'Tanzania', iso2: 'tz', code: '255' },
  { name: 'Thailand', iso2: 'th', code: '66' },
  { name: 'Timor-Leste', iso2: 'tl', code: '670' },
  { name: 'Togo', iso2: 'tg', code: '228' },
  { name: 'Tonga', iso2: 'to', code: '676' },
  { name: 'Trinidad and Tobago', iso2: 'tt', code: '1868' },
  { name: 'Tunisia', iso2: 'tn', code: '216' },
  { name: 'Turkey', iso2: 'tr', code: '90' },
  { name: 'Turkmenistan', iso2: 'tm', code: '993' },
  { name: 'Tuvalu', iso2: 'tv', code: '688' },
  { name: 'Uganda', iso2: 'ug', code: '256' },
  { name: 'Ukraine', iso2: 'ua', code: '380' },
  { name: 'United Arab Emirates', iso2: 'ae', code: '971' },
  { name: 'United Kingdom', iso2: 'gb', code: '44' },
  { name: 'United States', iso2: 'us', code: '1' },
  { name: 'Uruguay', iso2: 'uy', code: '598' },
  { name: 'Uzbekistan', iso2: 'uz', code: '998' },
  { name: 'Vanuatu', iso2: 'vu', code: '678' },
  { name: 'Venezuela', iso2: 've', code: '58' },
  { name: 'Vietnam', iso2: 'vn', code: '84' },
  { name: 'Wallis & Futuna', iso2: 'wf', code: '681' },
  { name: 'Yemen', iso2: 'ye', code: '967' },
  { name: 'Zambia', iso2: 'zm', code: '260' },
  { name: 'Zimbabwe', iso2: 'zw', code: '263' },
  { name: 'Canada', iso2: 'ca', code: '1' },
  { name: 'Caribbean Netherlands', iso2: 'bq', code: '599' },
  { name: 'Mayotte', iso2: 'yt', code: '262' },
  { name: 'Russia', iso2: 'ru', code: '7' },
  { name: 'Vatican City', iso2: 'va', code: '39' },
  { name: 'Dominican Republic', iso2: 'do', code: '1' },
  { name: 'Puerto Rico', iso2: 'pr', code: '1' },
  { name: 'Cayman Islands', iso2: 'ky', code: '1' },
]
